// Static fallback insult bank — used if the Groq call fails or is slow.
window.INSULT_BANK = [
  "bro really woke up and chose that",
  "the audacity of that face to just be out here like that",
  "u look like a rough draft that never got approved",
  "not the group chat's most reliable member showing up like this",
  "certified 'why is he like this' behavior",
  "that posture just filed a missing person report on your spine",
  "ur out here giving 'error 404: rizz not found'",
  "the AI paused, took a breath, and still had nothing nice to say",
  "u woke up and decided today was a beta test",
  "that's a whole personality crammed into one bad camera angle",
  "the algorithm looked at u and quietly unsubscribed",
  "not the main character, more like a background extra with commitment issues",
  "u give off 'wifi signal in the basement' energy",
  "even the ring light is embarrassed for u",
  "that's not a glow up, that's a glow sideways",
  "the camera zoomed in and immediately regretted it",
  "u look like a screenshot someone forgot to crop",
  "not u standing there like that's a personality trait",
  "that expression is doing unpaid overtime",
  "the mirror filed a formal complaint",
  "u really said 'let me try' and then didn't",
  "that's giving 'discontinued product' vibes",
  "the vibes are immaculate, the execution is not",
  "u look like a rough sketch someone abandoned",
  "not the confidence outpacing the results again",
  "that's a bold choice for someone being recorded",
  "the lighting is doing more work than u are",
  "u give 'placeholder image' energy fr",
  "that stance says 'I have not thought this through'",
  "not u testing the limits of what a face can do",
  "the webcam just sighed audibly",
  "that's a whole ted talk about poor decision making",
  "u look like the before picture in a before/after ad",
  "the AI ran the numbers and they weren't flattering",
  "not the posture giving 'I sit like this for fun'",
  "that's some real 'first day on the job' energy",
  "u really committed to that bit, respectfully, why",
  "the camera focused and somehow it got worse",
  "that's giving 'reply guy' energy and I don't know why",
  "u look like a NPC that glitched into main character mode",
  "not that face trying its hardest and still coming up short",
  "the resolution went up and so did the concerns",
  "that's a lot of confidence for zero results",
  "u give off 'forgot the assignment was due today' energy",
  "the AI is legally required to comment and this is what it came up with",
  "not the stance of someone who's never been told no",
  "that expression belongs in a museum, the 'what were they thinking' wing",
  "u look like u got dressed in the dark and it shows everywhere",
  "the camera has seen things, this might be a new low",
  "that's giving 'my wifi disconnected mid-thought' energy",
  "not u standing there like gravity owes u an apology",
  "the AI thought about being nice and then remembered its job",
  "u really said 'watch this' and then just stood there",
  "that posture is one bad decision away from a chiropractic emergency",
  "the vibe check failed and it wasn't close",
  "u give 'still loading' energy and it's been a minute",
  "that's a whole thesis on what not to do on camera",
  "not the confidence of a man who's never seen the replay",
  "the face is trying, the results disagree",
  "u look like a rough cut that needed one more edit",
  "that's giving 'submitted the wrong file' energy",
  "the AI paused mid-sentence to process what it just saw",
  "not that stance acting like it's a power pose",
  "u give off 'read the room never' energy",
  "that's a lot of screen time for very little payoff",
  "the camera zoomed out and it still didn't help",
  "u look like the rough draft of a much better idea",
  "that expression has never once been asked for",
  "not the posture of someone who's confident about this",
  "the AI ran a diagnostic and the results were humbling",
  "u give 'forgot what a mirror is for' energy",
  "that's giving 'permanently mid' and I stand by it",
  "the face said something, the vibes disagreed loudly",
  "u look like a placeholder that got promoted by accident",
  "not that stance thinking it's giving main character",
  "the AI would apologize but it's not wrong",
  "that's a bold interpretation of 'camera ready'",
  "u give off 'still figuring out how faces work' energy",
  "the resolution increased, the confidence did not deserve it",
  "not the posture doing its own thing entirely",
  "that expression is a cry for help disguised as confidence",
  "u look like the rough concept art before the real version",
  "the AI blinked, metaphorically, and still had thoughts",
  "that's giving 'never got the memo' energy consistently",
  "not u standing there like that's going great",
  "the camera captured it and immediately wanted a refund",
  "u give 'forgot to rehearse' energy every single time",
  "that's a whole seminar on things nobody asked to see",
  "the face is committed, the results are not grateful",
  "not that stance acting like it's earned confidence",
  "u look like an unfinished project that shipped anyway",
  "the AI processed the data and chose violence, respectfully",
  "that's giving 'still in beta' and it's not close to launch",
  "u give off 'read the instructions never' energy",
  "the posture filed for early retirement and nobody approved it",
  "not the expression doing the absolute most for the absolute least",
  "that's a rough way to find out cameras exist",
  "the AI thought twice and said it anyway",
  "u look like a rough draft of a rough draft",
  "that stance is a cry for structural support",
  "not the face acting like it's not being recorded",
  "the vibes took one look and left the chat",
  "u give 'still buffering' energy at all times",
  "that's giving 'submitted late and it shows' vibes",
  "the AI is contractually obligated to be honest right now",
  "not that posture pretending it's intentional",
  "u look like the concept, not the finished product",
  "the camera's autofocus gave up out of respect",
  "that's a lot of screen presence for very little reward",
  "the AI ran the math twice just to be sure, it checks out",
  "u give off 'forgot the camera was on' energy",
  "not the expression trying this hard for this little",
  "that stance is giving 'structural engineer needed'",
  "the face said a lot without saying anything good",
  "u look like a rough draft someone forgot to revise",
  "that's giving 'still working on it' after way too long",
  "the AI blinked twice, digitally, and had concerns",
  "not that posture committing to a bad bit",
  "u give 'error occurred while loading personality' energy",
  "the camera zoomed in for context and got none",
  "that's a bold move for someone who can be seen right now",
  "not the face acting like this is the final version",
  "u look like the placeholder text nobody replaced",
  "the AI ran out of nice things to say three insults ago",
  "that stance is doing a lot of unnecessary work",
  "the vibes are here, the execution filed for leave",
  "u give off 'still in the tutorial level' energy",
  "not that expression thinking it's pulling this off",
  "the AI would soften this but honestly, no",
  "that's a rough way to spend screen time",
  "u look like a work in progress with no deadline",
  "the posture said 'this is fine' and it was not fine",
  "not the face committing this hard to the bit",
  "that's giving 'forgot to check the mirror' energy",
  "the AI processed this and immediately had questions",
  "u give 'still installing updates' energy constantly",
  "that stance is one gust of wind from a headline",
  "not the expression thinking confidence fixes everything",
  "the camera captured it, science will study it later",
  "u look like the rough sketch nobody signed off on",
  "that's a whole lecture on what not to attempt on camera",
  "the AI has seen a lot and this still made the list",
  "not that posture acting like it's structurally sound",
  "u give off 'forgot the assignment existed' energy",
  "that expression is doing community service at this point",
];
